### ISSUE TITLE
Syntax error...

### ISSUE THREAD

**Issue by jdschwam** [timtomch/tnef2ics#1]
Hi.  This tool sounds very helpful.  Tried to run it and got:

[Running] /usr/bin/python "/Users/jdschwam/Scripts/tnef2ics-main/tnef2ics.py"
  File "/Users/jdschwam/Scripts/tnef2ics-main/tnef2ics.py", line 25
    def handle_starttag(self, tag: str, attrs):
                                 ^
SyntaxError: invalid syntax

[Done] exited with code=1 in 10.344 seconds

I do not now how to proceed.

Can you suggest something to try.

Or

Is there another tool that does .dat to .ics conversion for calendar information>. 

Thanks

**Comment by timtomch** [comment]
Hmm, that's odd. Can I ask if you downloaded my script directly or did you try and copy-paste it? Because this means the error is actually somewhere in the lines above line 25. Python uses indents as delimiters, and sometimes this can get borked when copy-pasting.

Also, which version of Pyhton are you running?

**Comment by jdschwam** [comment]
Hi Thomas,

Thank you for responding so quickly.  I iwll not be able to look into this until later in the week.  I will do that, check my verson and redownload the script.  The problem may simply be on my side.

I will let you know what I find and update my message.  

Thanks,

Dan


J Daniel Schwam
***@***.***
